#!/bin/bash

# 通用的commits合并脚本 - 自适应任何分支
# 将当前分支相对于master的所有commits合并为一个commit
# 使用方法: bash /Users/chenql/Desktop/workspace/code-review/rebase.sh [target_branch]

set -e  # 遇到错误时退出

# 显示帮助信息
if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    echo "📖 通用commits合并脚本使用说明"
    echo ""
    echo "功能："
    echo "  自动识别当前分支与master分支的分叉点（base），"
    echo "  将从base点到当前分支HEAD的所有commits合并为一个commit"
    echo ""
    echo "使用方法："
    echo "  bash $0 [target_branch]"
    echo ""
    echo "参数："
    echo "  target_branch  要处理的分支名（可选，默认为当前分支）"
    echo ""
    echo "示例："
    echo "  bash $0                    # 合并当前分支的commits"
    echo "  bash $0 feature-branch     # 合并指定分支的commits"
    echo ""
    echo "注意："
    echo "  - 脚本会自动创建备份分支"
    echo "  - 使用 git merge-base 智能识别分叉点"
    echo "  - 支持基于master历史任意commit的开发分支"
    exit 0
fi

# 参数处理
TARGET_BRANCH=${1:-$(git branch --show-current)}
MASTER_BRANCH="master"

echo "🔄 开始自适应合并commits..."
echo "🎯 目标分支: $TARGET_BRANCH"

# 切换到项目目录
cd /Users/chenql/Desktop/workspace/code-review/MindSpeed-MM

# 确保在目标分支上
current_branch=$(git branch --show-current)
if [ "$current_branch" != "$TARGET_BRANCH" ]; then
    echo "📝 当前分支: $current_branch，切换到目标分支: $TARGET_BRANCH"
    git checkout $TARGET_BRANCH
fi

# 获取最新的远程信息
echo "🔄 更新远程分支信息..."
git fetch origin

# 找到当前分支与master的最新公共commit（base点）
echo "🔍 寻找与master分支的公共base点..."

# 尝试不同的master分支引用
if git rev-parse --verify origin/master >/dev/null 2>&1; then
    MASTER_REF="origin/master"
elif git rev-parse --verify master >/dev/null 2>&1; then
    MASTER_REF="master"
else
    echo "❌ 找不到master分支，请检查分支名称"
    exit 1
fi

# 找到merge-base（最新公共祖先）
base_commit=$(git merge-base HEAD $MASTER_REF)
echo "📍 发现公共base点: $base_commit"
echo "📍 Base点信息: $(git log --oneline -1 $base_commit)"

# 计算需要合并的commits数量
commit_count=$(git rev-list --count $base_commit..HEAD)
echo "📊 需要合并的commits数量: $commit_count"

# 检查是否有commits需要合并
if [ "$commit_count" -eq 0 ]; then
    echo "ℹ️  当前分支与master分支同步，无需合并commits"
    exit 0
elif [ "$commit_count" -eq 1 ]; then
    echo "ℹ️  当前分支只有1个commit，无需合并"
    exit 0
fi

# 显示将要合并的commits
echo "📋 将要合并的commits:"
git log --oneline $base_commit..HEAD

# 用户确认
echo ""
echo "❓ 确认要将上述 $commit_count 个commits合并为一个吗？"
echo "   这将重写commit历史，原有的commits将被替换"
echo "   (会自动创建备份分支以便恢复)"
echo ""
read -p "请输入 'yes' 确认继续，或按Enter取消: " confirm

if [ "$confirm" != "yes" ]; then
    echo "❌ 操作已取消"
    exit 0
fi

# 获取要合并的commits信息用于生成commit message
commits_info=$(git log --pretty=format:"- %h: %s" $base_commit..HEAD | sed '1!G;h;$!d')
first_commit_subject=$(git log --pretty=format:"%s" $base_commit..HEAD | tail -1)
branch_name=$(git branch --show-current)

# 创建备份分支
backup_branch="backup-$branch_name-$(date +%Y%m%d-%H%M%S)"
echo "💾 创建备份分支: $backup_branch"
git branch $backup_branch

# 软重置到base commit，保留所有更改
echo "🔄 软重置到base点，保留所有更改..."
git reset --soft $base_commit

# 检查暂存区状态
echo "📋 暂存区状态:"
git status --short

# 动态生成commit message
echo "💾 创建合并后的commit..."
commit_message="[Feature] Combined commits from $branch_name

Auto-merged $commit_count commits into a single commit.
Based on: $(git log --oneline -1 $base_commit)

Original commits:
$commits_info

Changes include all modifications from the above commits.
Generated by automated rebase script."

# 执行commit
git commit -m "$commit_message"

echo "✅ 合并完成！"
echo "📋 新的commit历史:"
git log --oneline -3

echo ""
echo "🎉 成功将 $commit_count 个commits合并为一个！"
echo "📝 分支: $branch_name"
echo "📍 Base点: $(git log --oneline -1 $base_commit)"
echo "💾 备份分支: $backup_branch"
echo ""
echo "📌 如果需要推送到远程仓库，请使用:"
echo "   git push origin $branch_name --force-with-lease"
echo ""
echo "⚠️  注意事项:"
echo "   - 如果其他人也在使用这个分支，请谨慎使用force push"
echo "   - 已自动创建备份分支: $backup_branch"
echo ""
echo "🔄 如需恢复原状态，可以使用以下任一方法:"
echo "   方法1: git reset --hard HEAD@{1}"
echo "   方法2: git reset --hard $backup_branch"
echo "   方法3: git checkout $backup_branch && git branch -D $branch_name && git checkout -b $branch_name"
